// Generated by gencpp from file ros_tutorial_msgs/msgData.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MSGS_MESSAGE_MSGDATA_H
#define ROS_TUTORIAL_MSGS_MESSAGE_MSGDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorial_msgs
{
template <class ContainerAllocator>
struct msgData_
{
  typedef msgData_<ContainerAllocator> Type;

  msgData_()
    : angle()
    , mode(0)  {
      angle.assign(0.0);
  }
  msgData_(const ContainerAllocator& _alloc)
    : angle()
    , mode(0)  {
  (void)_alloc;
      angle.assign(0.0);
  }



   typedef boost::array<double, 3>  _angle_type;
  _angle_type angle;

   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::ros_tutorial_msgs::msgData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorial_msgs::msgData_<ContainerAllocator> const> ConstPtr;

}; // struct msgData_

typedef ::ros_tutorial_msgs::msgData_<std::allocator<void> > msgData;

typedef boost::shared_ptr< ::ros_tutorial_msgs::msgData > msgDataPtr;
typedef boost::shared_ptr< ::ros_tutorial_msgs::msgData const> msgDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorial_msgs::msgData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorial_msgs::msgData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_tutorial_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_tutorial_msgs': ['/home/robpang/pio_ws/src/ros_tutorial_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial_msgs::msgData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial_msgs::msgData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial_msgs::msgData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial_msgs::msgData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial_msgs::msgData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial_msgs::msgData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorial_msgs::msgData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b7cf6a5d1b828728f05b43a5c9cccb2";
  }

  static const char* value(const ::ros_tutorial_msgs::msgData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b7cf6a5d1b82872ULL;
  static const uint64_t static_value2 = 0x8f05b43a5c9cccb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorial_msgs::msgData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorial_msgs/msgData";
  }

  static const char* value(const ::ros_tutorial_msgs::msgData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorial_msgs::msgData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] angle\n\
uint8 mode\n\
\n\
";
  }

  static const char* value(const ::ros_tutorial_msgs::msgData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorial_msgs::msgData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorial_msgs::msgData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorial_msgs::msgData_<ContainerAllocator>& v)
  {
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angle[i]);
    }
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIAL_MSGS_MESSAGE_MSGDATA_H
