// Generated by gencpp from file ros_tutorial_msgs/srvTest.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MSGS_MESSAGE_SRVTEST_H
#define ROS_TUTORIAL_MSGS_MESSAGE_SRVTEST_H

#include <ros/service_traits.h>


#include <ros_tutorial_msgs/srvTestRequest.h>
#include <ros_tutorial_msgs/srvTestResponse.h>


namespace ros_tutorial_msgs
{

struct srvTest
{

typedef srvTestRequest Request;
typedef srvTestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvTest
} // namespace ros_tutorial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_tutorial_msgs::srvTest > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::ros_tutorial_msgs::srvTest&) { return value(); }
};

template<>
struct DataType< ::ros_tutorial_msgs::srvTest > {
  static const char* value()
  {
    return "ros_tutorial_msgs/srvTest";
  }

  static const char* value(const ::ros_tutorial_msgs::srvTest&) { return value(); }
};


// service_traits::MD5Sum< ::ros_tutorial_msgs::srvTestRequest> should match 
// service_traits::MD5Sum< ::ros_tutorial_msgs::srvTest > 
template<>
struct MD5Sum< ::ros_tutorial_msgs::srvTestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tutorial_msgs::srvTest >::value();
  }
  static const char* value(const ::ros_tutorial_msgs::srvTestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tutorial_msgs::srvTestRequest> should match 
// service_traits::DataType< ::ros_tutorial_msgs::srvTest > 
template<>
struct DataType< ::ros_tutorial_msgs::srvTestRequest>
{
  static const char* value()
  {
    return DataType< ::ros_tutorial_msgs::srvTest >::value();
  }
  static const char* value(const ::ros_tutorial_msgs::srvTestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_tutorial_msgs::srvTestResponse> should match 
// service_traits::MD5Sum< ::ros_tutorial_msgs::srvTest > 
template<>
struct MD5Sum< ::ros_tutorial_msgs::srvTestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tutorial_msgs::srvTest >::value();
  }
  static const char* value(const ::ros_tutorial_msgs::srvTestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tutorial_msgs::srvTestResponse> should match 
// service_traits::DataType< ::ros_tutorial_msgs::srvTest > 
template<>
struct DataType< ::ros_tutorial_msgs::srvTestResponse>
{
  static const char* value()
  {
    return DataType< ::ros_tutorial_msgs::srvTest >::value();
  }
  static const char* value(const ::ros_tutorial_msgs::srvTestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TUTORIAL_MSGS_MESSAGE_SRVTEST_H
